data:extend(
{
  {
    type = "int-setting",
    name = "lex-jet-volume-control-settings",
    setting_type = "startup",
    default_value = 5,
    allowed_values = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 },
    order = "a1",
  },
  {
    type = "double-setting",
    name = "lex-aircraft-scale-settings",
    setting_type = "startup",
    default_value =1,
    order = "a2",
  },
  {
    type = "double-setting",
    name = "lex-flying-cargo-speed-settings",
    setting_type = "startup",
    default_value = 100,
    order = "b1",
  },
  {
    type = "double-setting",
    name = "lex-flying-gunship-speed-settings",
    setting_type = "startup",
    default_value = 170,
    order = "b2",
  },
  {
    type = "double-setting",
    name = "lex-flying-heavyship-speed-settings",
    setting_type = "startup",
    default_value = 120,
    order = "b3",
  },
  {
    type = "int-setting",
    name = "lex-flying-cargo-inventory-size-settings",
    setting_type = "startup",
    default_value = 40,
    order = "c1",
  },
  {
    type = "int-setting",
    name = "lex-gunship-inventory-size-settings",
    setting_type = "startup",
    default_value = 10,
    order = "c2",
  },
  {
    type = "int-setting",
    name = "lex-flying-heavyship-inventory-size-settings",
    setting_type = "startup",
    default_value = 20,
    order = "c3",
  },
  -- {
  --   type = "bool-setting",
  --   name = "lex-flying-cargo-enable-logistics-settings",
  --   setting_type = "startup",
  --   default_value = true,
  --   order = "d1",
  -- },
  -- {
  --   type = "bool-setting",
  --   name = "lex-gunship-enable-logistics-settings",
  --   setting_type = "startup",
  --   default_value = false,
  --   order = "d2",
  -- },
  -- {
  --   type = "bool-setting",
  --   name = "lex-flying-heavyship-enable-logistics-settings",
  --   setting_type = "startup",
  --   default_value = false,
  --   order = "d3",
  -- },
  {
    type = "int-setting",
    name = "lex-flying-cargo-trash-inventory-size-settings",
    setting_type = "startup",
    default_value = 20,
    order = "d1",
  },
  {
    type = "int-setting",
    name = "lex-gunship-trash-inventory-size-settings",
    setting_type = "startup",
    default_value = 0,
    order = "d2",
  },
  {
    type = "int-setting",
    name = "lex-flying-heavyship-trash-inventory-size-settings",
    setting_type = "startup",
    default_value = 0,
    order = "d3",
  },

  
})